Vagrant.configure("2") do |config|

    config.ssh.insert_key = false
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "256"] 
    end

    # application server 1
    config.vm.define "app1" do |app|
        app.vm.hostname = "app1.dev"
        app.vm.box = "debian/bullseye64"
        app.vm.network "public_network"
    end

    # application server 2
    config.vm.define "app2" do |app|
        app.vm.hostname = "app2.dev"
        app.vm.box = "debian/bullseye64"
        app.vm.network "public_network"
    end

    # database server
    # config.vm.define "db" do |db|
    #     db.vm.hostname = "db.dev"
    #     db.vm.box = "debian/bullseye64"
    #     db.vm.network "public_network"
    # end

end

# ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkEYDqqjBADq70x0AuIl63du8hylkdHg6wMHdfPQwLXrstl9VlomGjMpo91EEvbg9oUq9crhAqYQNBod0nEcgV15cJStKb5xl3cLAdtmWRhEZWl8uA7ns0JRr6pj8fJH+RI2LFtxs7trj4J8poehxbBcC1uEsEE/Gxtf5MB35ZBI3+GwSgcLY6ZTy2HOTwuD8xsouI9qW5CwXbRHF7nElr6YQnpt5p+V675EQMZMZWIoZzFppRoPUcTnccxsK5EXbqQsVPKjU09GDOf3vyBp47WM1P6AfxVJs8sdCTwcb0xPmdEWLDw/GE47hLCAFht4kfIdcMtc8ukh+ePUPiyFrTpXVheUt2yFi3E7FwWYpTR4qKkhxpSydKNFQ5fcPWu/FemM6/ESui5ip33hDHv8m+ozTVohl4Q6PybccQR9KF8JmaMq1NfuT1CQKzHSlbNP3ieD5zqEZNmqujGOLmzaI0UP0yVtZTjKCVyLadW6fWy+KqejyyQKBhRhFa4K39FY0= root@bullseye
