- name: My Docker Playbook
  hosts: app
  remote_user: root
  tasks:
    - name: Remove old images
      docker_image:
        name: ironscar/spring-boot-docker
        tag: '{{spring_boot_docker.tag}}'
        state: present
        source: pull
    - name: Start new spring-boot container
      docker_container:
        name: spring-boot-docker
        image: ironscar/spring-boot-docker:{{spring_boot_docker.tag}}
        state: started
        detach: true
        cleanup: true
        ports: 8080:8081