- name: My Docker Playbook
  hosts: all
  remote_user: root
  tasks:
    - name: Start new spring-boot container
      docker_container:
        name: spring-boot-docker
        image: ironscar/spring-boot-docker:{{spring_boot_docker.tag}}
        env:
          app_sbd_prop1: "{{spring_boot_docker.app_sbd_prop1}}"
          app_sbd_prop2: "{{spring_boot_docker.app_sbd_prop2}}"
          app_sbd_pass: "{{spring_boot_docker.app_sbd_pass}}"
        state: started
        detach: true
        cleanup: true
        pull: "{{spring_boot_docker.override_image}}"
        ports: 8080:8081
    - name: Start spring-six-pro container
      docker_container:
        name: spring-six-pro
        image: ironscar/spring-six-pro:{{spring_six_pro.tag}}
        env:
          app_sql_db_url: "{{spring_six_pro.app_sql_db_url}}"
          app_sql_db_user: "{{spring_six_pro.app_sql_db_user}}"
          app_sql_db_pass: "{{spring_six_pro.app_sql_db_pass}}"
        state: started
        detach: true
        cleanup: true
        pull: "{{spring_boot_docker.override_image}}"
        ports: 8081:8081
    - name: Remove unused images
      docker_prune:
        images: true
        images_filters:
          dangling: false