- name: My Docker Playbook
  hosts: all
  remote_user: root
  tasks:
    - name: Start new spring-boot container
      docker_container:
        name: spring-boot-docker
        image: ironscar/spring-boot-docker:{{spring_boot_docker.tag}}
        env:
          app_sbd_prop1: "{{spring_boot_docker.app_sbd_prop1}}"
          app_sbd_prop2: "{{spring_boot_docker.app_sbd_prop2}}"
        state: started
        detach: true
        cleanup: true
        pull: true
        ports: 8080:8081
    - name: Remove unused images
      docker_prune:
        images: true
        images_filters:
          dangling: false