
Vagrant.configure("2") do |config|

  config.vm.box = "debian/bullseye64"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1536"
  end

  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update && sudo apt-get upgrade
  #   sudo apt-get install -y vim
  #   sudo apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
  #   sudo install -m 0755 -d /etc/apt/keyrings
  #   curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings01/docker.gpg
  #   sudo chmod a+r /etc/apt/keyrings01/docker.gpg
  #   sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  #   sudo apt-get update
  #   sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  #   sudo apt-get autoremove
  #   sudo usermod -aG docker vagrant
  # SHELL

end
